### ISSUE TITLE
bug:  --dump-env-script fails with OpenFOAM-4.0-intel-2016b.eb with: "

### ISSUE THREAD

**Issue by JackPerdue** [hpcugent/easybuild-framework#2251]
Related to #2111 (the buildenv module is new/neat and is a definite help but I'd still like the whole env, including dependencies for users who want to rebuild on their own)

```
[j-perdue@ada2 2017A-all]$ eb --dump-env-script   /tmp/OpenFOAM-4.0-intel-2016b.eb
== temporary log file in case of crash /tmp/j-perdue/tmp/eb-nFSl4t/easybuild-n3LULa.log
== resolving dependencies ...
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/general/software/x86_64/easybuild/software/EasyBuild/3.3.0/lib/python2.6/site-packages/easybuild_framework-3.3.0-py2.6.egg/easybuild/main.py", line 478, in <module>
    main()
  File "/general/software/x86_64/easybuild/software/EasyBuild/3.3.0/lib/python2.6/site-packages/easybuild_framework-3.3.0-py2.6.egg/easybuild/main.py", line 422, in main
    dump_env_script(easyconfigs)
  File "/sw/eb/software/EasyBuild/3.3.0/lib/python2.6/site-packages/easybuild_framework-3.3.0-py2.6.egg/easybuild/framework/easyconfig/tools.py", line 534, in dump_env_script
    app.prepare_step(start_dir=False)
TypeError: prepare_step() got an unexpected keyword argument 'start_dir'
[j-perdue@ada2 2017A-all]$ 
```

I've tried commenting out all dependencies in the easyconfig and commenting out the patch_step in the openfoam.py easyblock...  neither helped

```
[j-perdue@ada2 2017A-all]$ env | grep -e ^EB -e ^EASY -e ^MODULE -e ^LMOD | sort
EASYBUILD_BUILDPATH=/tmp/j-perdue/easybuild/
EASYBUILD_DEPRECATED=2.0
EASYBUILD_INCLUDE_EASYBLOCKS=/sw/eb/hprc/ec-dev/easyblocks/*.py
EASYBUILD_MINIMAL_TOOLCHAINS=1
EASYBUILD_MODULES_TOOL=Lmod
EASYBUILD_PREFIX=/sw/eb
EASYBUILD_READ_ONLY_INSTALLDIR=1
EASYBUILD_REPOSITORYPATH=/sw/eb/ebfiles_repo/ada
EASYBUILD_ROBOT=/sw/eb/ebfiles_repo_cleaned/ada
EASYBUILD_SOURCEPATH=/sw/eb/sources
EASYBUILD_TMPDIR=/tmp/j-perdue/tmp/
EASYBUILD_TMP_LOGDIR=/tmp/j-perdue/logs/
EB_ANSYS_LICENSE_SERVER=hprc-license.tamu.edu
EB_ANSYS_LICENSE_SERVER_PORT=2325:1055
EBDEVELEASYBUILD=/sw/eb/software/EasyBuild/3.3.0/easybuild/EasyBuild-3.3.0-easybuild-devel
EBROOTEASYBUILD=/sw/eb/software/EasyBuild/3.3.0
EBVERSIONEASYBUILD=3.3.0
LMOD_CMD=/sw/lmod/7.5.4/libexec/lmod
LMOD_DIR=/sw/lmod/7.5.4/libexec
LMOD_FULL_SETTARG_SUPPORT=no
LMOD_IGNORE_CACHE=1
LMOD_PACKAGE_PATH=/software/lmod/tamusc/modulefiles/
LMOD_PKG=/sw/lmod/7.5.4
LMOD_SETTARG_CMD=:
LMOD_sys=Linux
LMOD_VERSION=7.5.4
MODULEPATH_ROOT=/sw/lmod/hprc/mods
MODULEPATH=/software/tamusc/modulefiles:/software/easybuild/modules/all:/software/restricted/vasp/modulefiles:/sw/lmod/hprc/mods/Linux:/sw/lmod/hprc/mods/Core:/sw/lmod/lmod/modulefiles/Core
MODULESHOME=/sw/lmod/7.5.4
```
Any ideas?

**Comment by JackPerdue** [comment]
also tried unsetting EASYBUILD_MINIMAL_TOOLCHAINS  and setting EASYBUILD_ROBOT to '' (blank/nothing)... neither helped

**Comment by boegel** [comment]
@JackPerdue This is a problem in the OpenFOAM easyblock, I'll look into a fix.

**Comment by boegel** [comment]
Fixed in https://github.com/hpcugent/easybuild-easyblocks/pull/1202, let's follow up there

Thanks for reporting this @JackPerdue!
To fix the problem for OpenFOAM, see the (trivial) changes to the OpenFOAM easyblock here: https://github.com/hpcugent/easybuild-easyblocks/pull/1202/files#diff-0edc74d66adc49c07871a687be0ef167
